
export const metadata = {
  title: "Sameeksha",
  description: "Generated by Next.js",
};

export default  function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   
      
       <div>
        {children}
        <footer className='text-center p-4 md:p-3 bg-white dark:bg-mainDark dark:text-white'>
    Made in Bharat
  </footer>
      </div>
    
  );
}
